### ISSUE TITLE
References to resources

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#15]
@warmwaffles brought up the topic of references to resources in [#4](https://github.com/alteous/gltf/issues/4#issuecomment-288446269). Whilst it's probably infeasible to return such references directly from `import()`, it is certainly possible to write a wrapper around `Root` to 'walk the tree' using iterators.

Here is [experimental wrapper interface](https://github.com/alteous/gltf/blob/incoming/src/v2/tree.rs) and an [example of its usage](https://github.com/alteous/gltf/blob/incoming/examples/walk_tree/main.rs).

The question is, should the library provide this functionality and, if so, what design considerations need to be accounted for?

**Comment by warmwaffles** [comment]
> it is certainly possible to write a wrapper around Root to 'walk the tree' using iterators

You mean walk backwards on the tree all the way to the root?

**Comment by alteous** [comment]
> You mean walk backwards on the tree all the way to the root?`
Not quite, I mean to visit every node in a scene, exactly once, starting from the root nodes of the scene - I probably could have phrased that better. Does that make sense?

**Comment by warmwaffles** [comment]
That makes a little more sense.

The way I have been accessing it has been storing all of the nodes in a hash map, with the name as the key and the node as the value. And just doing manual look ups that way. I don't think there is going to be an easy solution to this to be honest. May just be better to keep it in the hash map form.

**Comment by alteous** [comment]
> May just be better to keep it in the hash map form.

I'm not proposing to replace the hash map form, that wouldn't be very reasonable. What I'm proposing is to introduce convenience methods to avoid doing the 'manual' lookups.

I'd imagine you have code that looks something like this (pseudo-code):
```rust

fn process_node(gltf: &Gltf, node: &Node) -> ... {
    for child_node_id in node.children {
        let child_node = gltf.nodes.get(child_node_id).unwrap();
        process_node(gltf, &child_node)?;
    }

    // We have to pass the root object around whenever we access other data
    let buffer_view = gltf.buffer_views.get(node.mesh.buffer_view).unwrap();
    ...
}

fn foo() -> ... {
    let gltf = Gltf::open("Foo.gltf")?;
    for scene in gltf.scenes.values() {
        for node_id in &scene.nodes {
            let node = gltf.scenes.get(node_id).unwrap(); // N.B. annoying unnecessary `unwrap()`
            process_node(gltf, &node)?;
        }
    }
    ...
}
```

There is a lot of cruft. The library would be a lot less painful to use if one could write something like this instead:
```rust

fn process_node(node: &tree::Node) -> ... {
    for child in node.iter_child_nodes() {
        process_node(child_node)?;
    }

    // Getting other data is now much simplier
    let buffer_view = node.mesh().buffer_view();
    ...
}

fn foo() -> ... {
    let gltf = Gltf::open("Foo.gltf")?;
    // This internally stores an reference to `gltf`
    let tree: tree::Root = gltf.tree();
    for scene in tree.iter_scenes() {
        for node = scene.iter_nodes() {
            process_node(node)?;
        }
    }
    ...
}
```
The benefit of this is debatable though since in practice you have to pre-load the buffer and texture data before building the scene, so you have to pass some data around anyway. This could be prevented however by loading such data on behalf of the user in the call to `tree()`, as you've suggested once before.

**Comment by alteous** [comment]
It is also noteworthy that whilst the node hierarchy of a 1.0 and 2.0 glTF scene is currently defined to be a [strict tree](https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#nodes-and-hierarchy), this is not guaranteed forever. The above would become difficult to implement properly if the node hierarchy allowed for cycles in a future release.

**Comment by warmwaffles** [comment]
> The above would become difficult to implement properly if the node hierarchy allowed for cycles in a future release.

And knowing the Khronos Group, it may just happen.

**Comment by alteous** [comment]
I think you're quite right. In that case these features would be best left for another 'unstable' crate, say `gltf-iter`, that could be deprecated if necessary.

**Comment by warmwaffles** [comment]
Or a feature flag that can be optionally included?

**Comment by alteous** [comment]
Good suggestion, that would make much more sense. It also carries the benefit of being automatically integration tested against changes to the core data structures.
