### ISSUE TITLE
gltf v2

### ISSUE THREAD

**Issue by MaikKlein** [alteous/gltf#17]
I have seen that you have started to support [v2](https://github.com/KhronosGroup/glTF/issues/605) in the [incoming](https://github.com/alteous/gltf/tree/incoming) branch. Would you say that it is already in a usable state?

**Comment by alteous** [comment]
It's certainly usable if you just want to deserialise .gltf files. I plan to merge this code when the official 2.0 specification is released. Until then the data structures are subject to change as the specification is finalised.

There are a few upcoming changes that you should prepare for however:

- All data structures in `v2` are to be moved into a sub module `v2::raw` to make way for the [upcoming wrapper interface](https://github.com/alteous/gltf/tree/tree).
- The `Extras` trait will be removed in favour of untyped `serde_json::Value`s.

**Comment by alteous** [comment]
Also, I forgot to mention, the `Get` and `TryGet` traits will probably be removed.
