### ISSUE TITLE
byteOffset seems to be optional

### ISSUE THREAD

**Issue by MaikKlein** [alteous/gltf#18]
The first bufferview in this file does not have a byteOffset.
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Lantern/glTF/Lantern.gltf#L237

I am not sure if there is a formal spec yet, but it probably should be default to 0 or optional. I'll understand if you want to wait until the spec has been finalized.

**Comment by MaikKlein** [comment]
https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#values

**Comment by alteous** [comment]
Well spotted. This is a bug.

**Comment by alteous** [comment]
There should be a `#[serde(default)]` on `byteOffset`.

**Comment by alteous** [comment]
I think they've all been fixed now. Thanks for reporting this.
