### ISSUE TITLE
Fix loading glTF 2.0 sample models

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#20]
@bwasty quite rightly reported that `tests/import_v2.rs` is failing on the latest 2.0 sample models.

On a side note, it would be worth rewriting the test to read the directory entries.

**Comment by bwasty** [comment]
Got another fix in progress (https://github.com/alteous/gltf/compare/incoming...bwasty:fix_box_loading) and found one issue was actually in the sample models: https://github.com/KhronosGroup/glTF-Sample-Models/issues/68.

**Comment by bwasty** [comment]
Done. I agree that `it would be worth rewriting the test to read the directory entries`, but for now I just wanted to quickly check if there are more issues, so I did it manually.

**Comment by alteous** [comment]
Thanks for fixing this.

FYI I'm currently rewriting the tests.
