### ISSUE TITLE
Should glTF 1.0 support be discontinued?

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#27]
I am tempted to deprecate the `v1` module and remove it in the planned `1.0.0` release. The contents of the `v2` module would then be moved to the crate root.

**Rationale**

- The `v1` module feels like legacy code in which I am not personally interested in maintaining.
- I'm skeptical whether anybody is using the `v1` module since it's far more restrictive than 2.0.
- The crate could be better organised without having two separate modules.
- More attention can be focused on glTF 2.0, and especially on the wrapper interface.

Until now there has been a lot of hard work to get the 1.0 version up to scratch. It would be a shame to abandon it entirely. Perhaps it could be migrated to another crate, say `gltf-legacy`?

Personally, I would like to see glTF 2.0 become a widely adopted 3D interchange format. I think having a solid idiomatic Rust library for glTF 2.0 will encourage game / graphics development in Rust and help support glTF 2.0 adoption, which is one of the main reasons I began working on `gltf` in the first place.

If you are actively using the `v1` module, please speak out now!

**Comment by bwasty** [comment]
I'm all for deprecating/removing.

**Comment by bwasty** [comment]
Instead of a legacy crate it could be enough to add a note to the readme saying the last version supporting glTF 1.0 is 0.5.

**Comment by alteous** [comment]
Adding a note to the readme is a good idea.

The rationale behind the `gltf_legacy` crate is that the old `v1` code is available for anybody to easily fork and / or submit pull requests. If a new major spec is released (perish the thought!) then the current code could be moved to `gltf_legacy::v2` likewise.

**Comment by fst3a** [comment]
I'm against deprecation of glTF 1.0 (I am also willing to maintain it) as certain tools are not mature to work with glTF 2.0.

**Comment by alteous** [comment]
I'm curious: What are the certain tools?

**Comment by fst3a** [comment]
Well for one, khronos' glTF 2.0 import-export plugin for Blender is still in development as of now and is pain to install + comes with some bugs (that are not present in the other plugin that can export only glTF1).

**Comment by alteous** [comment]
It is to be expected that glTF 2.0 tools are incomplete (even this library is incomplete) since the specification was only formally released a week ago.

I believe the glTF 2.0 specification to be superior, mainly due to the shaders being replaced with PBR materials. If there is a demand for glTF 1.0 in Rust applications then of course the `v1` module should not be deprecated, however I doubt this will be the case.

What motivates you to want to maintain the `v1` module? Are you planning to use glTF 1.0 in any of your projects?

**Comment by fst3a** [comment]
Alright, fair.

**Comment by alteous** [comment]
Final decision: glTF 1.0 will not be supported in the 1.0 release.
