### ISSUE TITLE
enum_number/string for v2?

### ISSUE THREAD

**Issue by MaikKlein** [alteous/gltf#29]
See https://github.com/alteous/gltf/blob/master/src/v1/json/accessor.rs#L11 and https://github.com/alteous/gltf/blob/master/src/v1/json/accessor.rs#L24

Is there a reason why v2 doesn't have those enums?

**Comment by MaikKlein** [comment]
Never mind, I see that the incoming branch has those constants. https://github.com/alteous/gltf/blob/incoming/src/json/accessor.rs#L14

**Comment by alteous** [comment]
FYI, the `enum_number` and `enum_string` were used for validation during deserialisation and have since been removed to separate these concerns.
