### ISSUE TITLE
New BoxInterleaved sample model fails to load (wrapper branch)

### ISSUE THREAD

**Issue by bwasty** [alteous/gltf#32]
The new model introduced in https://github.com/KhronosGroup/glTF-Sample-Models/pull/84 makes the tests fail with 
```
---- import stdout ----
	"./glTF-Sample-Models/2.0/BoxInterleaved/glTF/BoxInterleaved.gltf": Io(
    Error {
        repr: Os {
            code: 2,
            message: "No such file or directory"
        }
    }
)
thread 'import' panicked at 'explicit panic', tests/import_examples.rs:18
```

**Comment by alteous** [comment]
This is because the tests assume each glTF has a path of the form Foo/glTF/Foo.gltf, but the BoxInterleaved example has corresponding path "./glTF-Sample-Models/2.0/BoxInterleaved/glTF/Box_Interleaved.gltf" - note the underscore. This is quite annoying.

**Comment by bwasty** [comment]
Maybe the tests could be changed to scan for all .gltf and .glb files, without relying on a convention. There are often different numbers of subfolders with different variations of the models that could also be tested (maybe exclude certain folder patterns if the extension is not supported).

**Comment by alteous** [comment]
The BoxInterleaved test should be fixed now - see https://github.com/KhronosGroup/glTF-Sample-Models/pull/88.

Scanning for .gltf / .glb files is a future-proof solution, I guess. The [`walkdir`](https://crates.io/crates/walkdir) crate should make that fairly simple.

**Comment by bwasty** [comment]
Yes, works now; even renders fine :)
So - close or implement scanning first?

**Comment by alteous** [comment]
The issue has been resolved; I'll open a new issue for the test.
