### ISSUE TITLE
Implement binary glTF importer

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#35]
This is pretty much done, but needs some testing.

**Comment by bwasty** [comment]
Speaking of testing: coverage might be nice -> https://medium.com/@Razican/continuous-integration-and-code-coverage-report-for-a-rust-project-5dfd4d68fbe5.

**Comment by alteous** [comment]
> coverage might be nice

I'm not sure how to respond to this right now. Code coverage is helpful for identifying areas where testing may be lacking but I don't think it's a good measure of test quality. Let's revisit this once some non-trivial tests have been written.
