### ISSUE TITLE
Implement image decoding

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#37]
This should happen during the import process. The only valid MIME types in core glTF are `image/jpeg` and `image/png`, however we should try to abstract over image decoding to account for new formats, user specific formats, and image extensions.

**Comment by bwasty** [comment]
I saw you added the `jpeg-decoder` and `png` crates directly - for more abstraction it the `image` crate might be better ([example code](https://github.com/bwasty/learn-opengl-rs/blob/17b09fbf93d6c81f95c127f58ee2cb3efee44c92/src/model.rs#L117-L125))
It looks like users can't directly add new custom formats, but there is an `ImageDecoder` trait.

**Comment by alteous** [comment]
I was avoiding the `image` crate because it doesn't follow standard Rust conventions - I don't want to encourage that. On closer inspection however neither do `jpeg-decoder` nor `png`!

**Comment by bwasty** [comment]
Which conventions? I didn't notice anything while using it. And is there a real alternative? As far as I saw, it's the only general-purpose image loader.

And about leaving it to the `Source` trait - my initial expectation was that the library would only load raw binary data, leaving the rest to the user (e.g. `image::load_from_memory` after import).
If it's in the `Source` trait it might be difficult to provide a good default one for just loading everything from disk.

**Comment by alteous** [comment]
> Which conventions?

Naming things, mostly: 

* `ImageError` and `ImageFormat` instead of `image::Error` and `image::Format` etc.
* Capitalised enum names such as `ImageFormat::JPEG` instead of `Format::Jpeg` etc.
* `raw_pixels` instead of `into_raw_pixels`.

These are among the oddities I've found so far. Unfortunately, as you rightly mention, there is no reasonable alternative.

> I think it would be best to leave image decoding to the Source trait.

What I mean here is to let the user load and decode image data in their custom `Source`. The reference implementation (`FromPath`) currently uses `image::load_from_memory_with_format` but only if the mime type is `image/jpeg` or `image/png`.

I think you raise a good point about images being decoded during import. Currently, the importer loads and decodes all images during import. This may be a waste of resources if the images are never read. If the library opts for 'lazy-loading' however then this isn't a concern because the images will have to be decoded immediately after the data is received.

**Comment by alteous** [comment]
Postponed.
