### ISSUE TITLE
What is incomplete and still left to do?

### ISSUE THREAD

**Issue by warmwaffles** [alteous/gltf#4]
I'm interested in working to get this lib up to GLTF 1.0 compliant.

Definitely need to add more tests in to ensure that it is 1.0 compliant.

How are buffer binary files going to be handled? 
Should this library load them up into memory? Lazy load?
Buffers can be base64 encoded uri's which I don't know if it is decoded.

### Side notes

There is a spec for 2.0 that is currently under way and they introduce a `.glb` format which from the looks of it, is just the binary gltf extension.

* https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/GLB_FORMAT.md
* https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF

In 2.0 it looks like they are going to pull the shader code stuff out of the spec and make it an extension instead. https://github.com/KhronosGroup/glTF/tree/2.0/extensions/Khronos/KHR_technique_webgl

**Comment by alteous** [comment]
Thanks for getting involved. Currently the library is ~50% conforming to the 1.0 specification.

## Implementation status of top-level objects

Below lists the current status of the library in terms of 1.0 conformance. I derived this information from the [properties reference](https://github.com/KhronosGroup/glTF/blob/master/specification/1.0/README.md#properties-reference) of the specification.

### Complete
- `accessor`
- `asset`
- `buffer`
- `bufferView`
- `material`
- `mesh`
- `primitive`
- `program`
- `shader`
- `technique`

### Partially complete
- `glTF` (root object) is missing the following fields:
  - `animations`
  - `cameras`
  - `extensions`
  - `extensionsUsed`
  - `extras`
  - `images`
  - `nodes`
  - `samplers`
  - `scene`
  - `scenes`
  - `skins`
  - `textures`
- `node` is missing the following fields:
  - `camera`
  - `children`
  - `skeletons`
  - `skin`
  - `jointName`
  - `matrix`
  - `rotation`
  - `scale`
  - `translation`
  - `name`

### Unimplemented
 - `animation`
 - `camera`
 - `image`
 - `sampler`
 - `scene`
 - `skin`
 - `texture`

## Design principles

When I starting writing this library I had two main design principles in mind. They are open for debate.

- Extra processing should be opt-in
  - By default the library should do as little as possible
  - We could provide import configuration to pre-load buffers etc
  - base64 encoded buffers should remain base64 for now
- Conformance to specification is more important than being fully-featured

Perhaps this should be added to the front page?

## Remarks

I'm very pleased to hear that the 2.0 spec is removing the shader dependency, this caused a lot of friction in my personal projects!

**Comment by warmwaffles** [comment]
It's probably best to get to full conformance before diving in to adding facilities to extract the binary data out to push into opengl.

**Comment by alteous** [comment]
Which parts are you currently working on? We could split the workload if you'd prefer. FYI I've [drafted an implementation of the 2.0 spec](https://github.com/alteous/gltf/tree/2.0-spec-draft) which reorganises the project slightly but keeps the original content largely unchanged. The reorganisation was necessary because the library is not prepared to cater for multiple glTF versions.

There are two notable differences between the implementations:
1. In v100.rs the `Id` type is an untyped `String` whereas in v200.rs it is a typed `u32`. It would probably be beneficial to convert the former to a typed `String`.
2. v200.rs does not implement the `Find` trait because I think it should be abolished.

**Comment by warmwaffles** [comment]
I needed to become familiar with the 1.0 spec again and reimplemented it based on what you had done previously. I'll push it to a scratch branch and I don't expect it to merge but something to think about.

Made quick little binary to load and print the glTF data structure to the console. I loaded all of the 1.0 sample models pretty fine.

### Some caveats

  1. I made `Id` back to `String` because it was easier to do so. This is only temporary until later
  2. Moved each set of resources into their own module. IE `buffer::Buffer`, `buffer::BufferView`, etc...
  3. There is no public fields on the structs
  4. Extra and Extensions are not supported (don't currently have a solution that doesn't involve some sort of messed up hash map and internal serde knowledge to the person consuming it)

### Goals

What I want to explore is deserializing the file into a well formed tree struct that doesn't require knowledge about how glTF actually operates. Conversely I want to explore serializing the glTF structure automatically so that way you could in theory programmatically build a scene.

I want to access the gltf structure via public methods as opposed to fiddling with a HashMap directly. Instead I would love to hide that detail from the consumer and use something like `gltf.get_node("Car")` and be able to get all of the resources associated to that car via accessor methods on that node as well.

```rust
let car: node::Node = gltf.get_node("Car");
let mesh: mesh::Mesh = car.get_mesh();
```

Overall I'd like the only string I would have to initially use is using it to get the initial model to load and then traverse the entire dependency tree to get all the resources and pump them into opengl.

**Comment by warmwaffles** [comment]
Here is what I quickly hashed out last night https://github.com/alteous/gltf/compare/master...warmwaffles:exploration

**Comment by warmwaffles** [comment]
Thinking about it now, your initial implementation makes sense. Some other library would consume this structure and hide it from the consumer of it.

**Comment by warmwaffles** [comment]
I've got the integer types coerced into enums and coerced back to their integer values.

Missing tests, which will be added soon

**Comment by alteous** [comment]
This is great. The branch shouldn't cause too many conflicts for merging - I'm happy to fix the conflicts manually if necessary.

A few comments:
- The idea of having a well-formed data structure is attractive but as you've probably realised this is not straightforward without duplicating data (the meshes in your example) or resorting to unsafe code.
- I've implemented a [`impl_enum_string!`](https://github.com/alteous/gltf/blob/2.0-spec-draft/src/macros.rs#L2) macro similar to `enum_number!` that you might find useful.
- Turning `Id` into `Id<T>` is a bit more complex in 1.0. [Here's one possible implementation](https://gist.github.com/alteous/f84ceea615c4359f2d038a00f77ed18f) using an extra `RootObject` trait to enforce the prefix convention.
- Being about to export glTF would be a great future feature. I'm considering a builder struct `GltfBuilder` where we could make guarantees of the validity of references the users provides, but personally I'd rather concentrate on just loading at the moment.

Minor gripes:
- `Texture2D` should be `Texture2d` (consider a type named `Texture2DIter` vs `Texture2dIter`)
- The Rust [convention](https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis) for getters doesn't have the `get_` prefix

**Comment by warmwaffles** [comment]
Your minor gripes are valid. I'll rename the Texture2D, and `get_` idea is kind of debunked since I made everything public again.

I'll open a PR against `v0.4.0` and make the necessary modifications to get it to not conflict on merging. I'll move the little binary debugger out into an example or tool directory to tinker with.

> I've implemented a impl_enum_string! macro similar to enum_number! that you might find useful.

Clever, I'll swing that enum string together.

> I'd rather concentrate on just loading at the moment

I hear you on that. I thought about making a `gltf_viewer` outside of this library to consume it and render the model on screen. Probably a good way to visually check the models loading and ensuring robustness on loading.

Besides, I think Kronos offers a solution to export a Collada to glTF that you can use in the mean time to get everything ready to roll.

**Comment by warmwaffles** [comment]
Some things I see left to do:

1. Translating some strings into enums
2. Making tests around malformed data being passed not causing a panic, but rather a `Result<Err>` of sorts.
3. Making resources hold a reference to the parent gltf structure?

**Comment by alteous** [comment]
I have some concerns regarding the user friendliness of the library that I would like to address soon, perhaps in the next release.
- Matching on enums is preferable to matching on strings, as you've already identified.
- Getting uniform values out of `Material` is a [very painful process](https://gist.github.com/alteous/0ac359cf59c2f2a0e40d32df476c75b7) (this isn't even complete). It would be a reasonable trade-off to spend some CPU time post-processing this data into something more manageable.
- Obtaining references to top-level objects (i.e. accessing the hash maps) should not return `Option<T>` because we (should) know that the references are valid ahead of time. This is quite a burden from the user's perspective.
- Of course, if the user decides to remove items from the top-level maps then we can't guarantee the references any longer, so I propose we enforce immutability on the top-level object. If necessary, we can provide `fn as_mut()` at a later date and then let the user deal with the `Option<T>` madness that ensues.

**Comment by warmwaffles** [comment]
Can we combine both https://github.com/alteous/gltf/tree/2.0-spec-draft and https://github.com/alteous/gltf/tree/v0.4.0 into a single branch?

**Comment by alteous** [comment]
Sure, I'll do it after #10 is merged.
