### ISSUE TITLE
Fix data URI decoding

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#46]
`gltf-viewer /home/alteous/gltf/glTF-Sample-Models/2.0/VC/glTF-Embedded/VC.gltf` fails with error `Source(Io(Error { repr: Os { code: 36, message: "File name too long" } }))`. This is because the URI has MIME type `data:image/jpeg;base64`, which isn't explicitly handled by `FromPath`.

Suggested fix: Use the `mime` crate or otherwise to parse the data URI and handle loading in a more robust way.

**Comment by bwasty** [comment]
I just looked into this and noticed the data URI handling is directly in the `FromPath` source. Couldn't the calling functions (`source_buffers`/`source_images`) handle this? I don't think custom sources will want to override/re-implement this.

**Comment by alteous** [comment]
Yes, it would probably be a better idea to move this code out of `FromPath`.

**Comment by alteous** [comment]
This code has been moved to `gltf-importer`, but is otherwise still unfixed.

**Comment by alteous** [comment]
Fixed in 0.9.
