### ISSUE TITLE
Report anomalies in documentation here

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#49]
A large part of the wrapper interface was generated from a script and so contains minor errors here and there.

**Comment by bwasty** [comment]
Wrong mentions of "index" where it's actually a reference:
https://docs.rs/gltf/0.7.0/gltf/texture/struct.Texture.html#method.sampler
https://docs.rs/gltf/0.7.0/gltf/texture/struct.Texture.html#method.source

https://docs.rs/gltf/0.7.0/gltf/skin/struct.Skin.html#method.inverse_bind_matrices
https://docs.rs/gltf/0.7.0/gltf/skin/struct.Skin.html#method.joints
https://docs.rs/gltf/0.7.0/gltf/skin/struct.Skin.html#method.skeleton

https://docs.rs/gltf/0.7.0/gltf/animation/struct.Sampler.html#method.input
https://docs.rs/gltf/0.7.0/gltf/animation/struct.Sampler.html#method.output

**Comment by alteous** [comment]
Great, thanks!

**Comment by alteous** [comment]
Fixed in `simplify`.
