### ISSUE TITLE
Make image loading opt-out

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#51]
Buffer data is required to be loaded so that accessors can iterate over the data etc. Image data however has no real reason to be preloaded other than for convenience. Some rendering APIs, notably three-rs, only allows loading images from a path, so preloading this data is a complete waste of resources.

**Comment by Ralith** [comment]
It'd be nice if this was specifically a cargo feature, so it doesn't even need to be compiled.

**Comment by alteous** [comment]
Closed for the same reason as https://github.com/alteous/gltf/issues/53

**Comment by anderejd** [comment]
> Closed for the same reason as https://github.com/alteous/gltf/issues/53

#53 gives 404, what was the reason?
