### ISSUE TITLE
Redesign Image type

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#53]
The current `Image` abstraction is too basic. It ought to be redesigned with at least the following features:

 - Ability to obtain dimensions in pixels (N.B. all glTF images are 2D.)
 - Ability to obtain the pixel format, e.g. `Rgb`.

A nice-to-have feature would be to be able to choose the pixel type, i.e. `u8` or `f32` etc.

I considered briefly re-exporting `DynamicImage` from the `image` crate but gut feeling tells me that's not a good idea. We could design the image abstraction closely following this type, however - perhaps even providing `From` / `Into` conversions.

Here's a draft of my ideas:

```rust
#[derive(Clone, Debug)]
pub enum Image<T: Copy> {
    Gray(Vec<[T; 1]>),
    GrayAlpha(Vec<[T; 2]>),
    Rgb(Vec<[T; 3]>),
    Rgba(Vec<[T; 4]>),
}

impl From<image::DynamicImage> for Image<u8> { ... }
impl Into<image::DynamicImage> for Image<u8> { ... }
```

On a side note there are lots of image types now, for example `image::Image`, `json::image::Image`, `extensions::image::Image`, `json::extensions::image::Image`, `import::data::AsyncImage`, `import::data::EncodedImage`, etc. Is this getting out of hand?!

**Comment by alteous** [comment]
Also, we might want to consider auto-resizing non-power-of-two textures. The specification says this should be performed at runtime.

**Comment by bwasty** [comment]
I don't have an opinion about the type (works fine for me), but it might be worth having resizing of NPOT textures in the library. And part of the necessary checks could be exposed as a `needs_mipmap()` function. Basically what's in [here](https://github.com/bwasty/gltf-viewer/blob/443151ecb7ddd690be272c1cdadffbe2b3916151/src/render/texture.rs) apart from the GL calls.

**Comment by alteous** [comment]
Closed since image processing will be delegated to the user in future versions.
