### ISSUE TITLE
Fix Texture::sampler default case

### ISSUE THREAD

**Issue by bwasty** [alteous/gltf#56]
Analogous to #48, `sampler` should not return an `Option`, but a `Sampler` with default values.
[Docs](https://docs.rs/gltf/0.7.0/gltf/texture/struct.Texture.html#method.sampler)
[Spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#texture): 
> The index of the sampler used by this texture. When undefined, a sampler with repeat wrapping and auto filtering should be used.

**Comment by alteous** [comment]
Thanks for reporting!
