### ISSUE TITLE
License doesn't need to have all the dependencies listed

### ISSUE THREAD

**Issue by warmwaffles** [alteous/gltf#6]
Each of those dependencies have their own license associated with it. Since you aren't including their source code, it isn't necessary to have all of them included.

**Comment by alteous** [comment]
It's probably worth relicensing the library under a [dual MIT/Apache 2.0 licence](https://github.com/diesel-rs/diesel/issues/82) similar to [rustc](https://github.com/rust-lang/rust#license).
