### ISSUE TITLE
Make iterators ExactSizeIterator

### ISSUE THREAD

**Issue by fst3a** [alteous/gltf#64]
I think considering that gltf is non-streaming format it's fair to implement ExactSizeIterator for iterators that are giving out gltf's objects

**Comment by alteous** [comment]
https://github.com/alteous/gltf/pull/61 was very recently merged into `incoming` for precisely this issue.

**Comment by alteous** [comment]
Is there anything missing?

**Comment by fst3a** [comment]
Huh, seems to be ok, I didn't check incoming at first, sorry

**Comment by alteous** [comment]
No need to apologise - it's just quite funny that you brought this up literally a couple of hours after I'd made the change!
