### ISSUE TITLE
Generate tangents and normals

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#65]
Generating tangents and normals has been an elephant-in-the-room for a while. The specification says we should use the mikktspace algorithm when tangents are not provided and compute flat normals when normals are not provided. There is an important caveat, namely the mikktspace algorithm reorders the existing geometry, and flattens any original index list - that is, the output data is suitable for `glDrawArrays`. We have to recreate a new index list ourselves if wanted.

**Read ahead for new ideas and updates**

I propose the following ideas to deal with these concerns. (N.B. this is pseudo-code and probably won't compile.)

```rust
/// Geometry to be rendered with the given material.
#[derive(Clone, Debug)]
pub struct Primitive<'a>  {
    /// The parent `Mesh` struct.
    mesh: &'a Mesh<'a>,

    /// The corresponding JSON index.
    index: usize,

    /// The corresponding JSON struct.
    json: &'a json::mesh::Primitive,

    /// New: Computed vertex normals.
    computed_normals: Option<Vec<[f32; 3]>>,
}

impl<'a> Primitive<'a> {
    /// Same as before, returning `None` if there are no tangents available.
    pub fn tangents(&self) -> Option<Tangents<'a>> {
        self.find_accessor_with_semantic(Semantic::Tangents)
    }

    /// New function: Generates flat normals, returning `None` if there are no positions available.
    pub fn normals(&mut self) -> Option<Normals<'a>> {
        if let Some(iter) = self.find_accessor_with_semantic(Semantic::Normals) {
            Normals(Either::Left(iter))
        } else {
            let normals = self.computed_normals
                .as_ref()
                .unwrap_or_else(|| self.compute_normals());
            Normals(Either::Right(normals.iter()))
        }
    }

    /// New function: Generates tangents, returning `None` if there the primitive lacks positions
    /// or texture co-ordinates - we can generate the normals if necessary.
    pub fn mikk_tspace(self) -> MikkTSpace<'a> {
         // *Magic*
    }
}

/// We might have to duplicate all the other iterators.
/// Alternatively, iterators could take an ordering argument instead. (`Incremental` or `Explicit`)
pub mod mikk_tspace {
    /// New: Geometry guaranteed to have positions, normals, and tangents, but not in original order.
    #[derive(Clone, Debug)]
    pub struct MikkTSpace<'a>  {
        /// The original `Primitive` struct.
        original: &'a Primitive<'a>,

        /// New ordering of vertex data.
        ordering: Vec<u32>,

        /// Newly computed tangents.
        tangents: Vec<[f32; 4]>,

        /// Newly computed index list.
        indices: Vec<u32>,
    }

    /// New: Example color iterator.
    pub struct Colors<'a> {
        original: &'a super::Colors<'a>,
        order: &'a [u32],
    }

    impl<'a> Iterator for Colors<'a> {
        type Item = [f32; 4];
        fn next(&mut self) -> Option<Self::Item> {
            self.order.map(|index| self.original.iter().nth(index).unwrap())
        }
    }
}
```

**Comment by bwasty** [comment]
A nicer interface might be a flag in the import config. Then the primitive parsing code (user side) would not need to distinguish between 'normal' tangents and `mikk_tspace` tangents.

I'm not sure re-indexing is worth the effort at the moment - my guess is that big, complex models where it might make a significant performance difference will usually already have tangents.

**Comment by alteous** [comment]
Not sure about the import config flag. The specification says the client is required to generate tangents when unavailable and also to support at least two texture co-ordinates, and one vertex color (amongst others.)

Removing the distinction between regular and mikktspace tangents is a good point, however, and would be beneficial to the user. I propose, instead of the idea in the OP, that the primitive automatically generates normals / tangents upon creation, and that process is not configurable by the user.

> big, complex models where it might make a significant performance difference will usually already have tangents

Agreed, although it isn't a lot of extra effort regenerating the index list - we can use [`genmesh::LruIndexer`](https://docs.rs/genmesh/0.5.0/genmesh/struct.LruIndexer.html).

**Comment by alteous** [comment]
Representing all the different `Option<Position>` / `Option<Normal>` / `Option<Tangent>` / `Option<TexCoord>` / `Option<Color>` combinations etc. etc. etc. is becoming increasingly difficult through the type system. Perhaps we should provide a basic vertex type that covers all the mandatory elements (which configurable defaults) and provide a `bitflags` type to let the user query what was provided / generated at runtime?

**Comment by alteous** [comment]
```rust
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Vertex {
    position: [f32; 3],
    normal: [f32; 3],
    tangent: [f32; 4],
    tex_coord_0: [f32; 2],
    tex_coord_1: [f32; 2],
    color_0: [f32; 4],
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SkinnedMeshVertex {
    position: [f32; 3],
    normal: [f32; 3],
    tangent: [f32; 4],
    tex_coord_0: [f32; 2],
    tex_coord_1: [f32; 2],
    color_0: [f32; 4],
    joints_0: [u16; 4],
    weights_0: [f32; 4],
}

bitflags! {
    pub struct Flags: u32 {
        const POSITION   = 1 << 0;
        const NORMAL     = 1 << 1;
        const TANGENT    = 1 << 2;
        const TEXCOORD_0 = 1 << 3;
        const TEXCOORD_1 = 1 << 4;
        const TEXCOORD_N = 1 << 5 | TEXCOORD_0 | TEXCOORD_1;
        const COLOR_0    = 1 << 6;
        const COLOR_N    = 1 << 7 | COLOR_0;
        const JOINTS_0   = 1 << 8;
        const JOINTS_N   = 1 << 9 | JOINTS_N;
        const WEIGHTS_0  = 1 << 10;
        const WEIGHTS_N  = 1 << 11 | WEIGHTS_0;
    }
}
```

**Comment by alteous** [comment]
> Implementation Note: A node definition does not specify whether the node should be treated as a joint. Client implementations may wish to traverse the skins array first, marking each joint node.

Perhaps we should do this too?

**Comment by alteous** [comment]
What if we split the primitive iterator into three separate iterators?

```rust
/// An `iterator` that visits the primitives of a mesh.
struct Primitives { ... }

impl Iterator for Primitives {
    type Item = (Option<Geometry>, Option<Decoration>, Option<Skinning>, Option<Extras>);
    fn next(&mut self) -> Option<Self::Item> {
        // If positions are provided, generate normals and tangents (if necessary) and return `Some(Geometry)`.
        // If texture co-ordinates or vertex colors are provided, return `Some(Decoration)`.
        // If joints and weights are provided, return `Some(Skinning)`.
        // If anything else is provided, return `Some(Extras)`.
    }
}

**Comment by alteous** [comment]
- `Geometry`
   - `POSITION`
   - `NORMAL`

- `Decoration`
   - `TANGENT` <- N.B!
   - `TEXCOORD_0`
   - `TEXCOORD_1`
   - `COLOR_0`

- `Skinning`
   - `JOINTS_0`
   - `WEIGHTS_0`

- `Extras`
   - `TEXCOORD_N`
   - `COLOR_N`
   - `JOINTS_N`
   - `WEIGHTS_N`
   - `_USER_XXX`

**Comment by alteous** [comment]
^^ I very much like this idea.

**Comment by alteous** [comment]
Draft:

```rust
    /// Splits the primitive into its four major categories.
    ///
    /// * Where `POSITION` is provided, the function will return
    ///   `Some(Positioning)` with computed flat normals if `NORMAL`
    ///   was not provided also.
    ///
    /// * Where `TANGENT` is provided, the function will return
    ///   `Some(Texturing)` along with any provided texture co-ordinates.
    ///
    /// * Where `TANGENT` is not provided but `TEXCOORD_0` is, the function
    ///   will return `Some(Texturing)` with computed tangents along with any
    ///   provided texture co-ordinates.
    ///
    /// * Where `COLOR_0` is provided, the function will return `Some(Coloring)`
    ///
    /// * Where `JOINTS_0` and `WEIGHTS_0` are provided, the function will return
    ///   `Some(Skinning)`.
    pub fn split(&self) -> (
        Option<Positioning>,
        Option<Texturing>,
        Option<Coloring>,
        Option<Skinning>,
    ) {
        // TODO
    }
```

**Comment by alteous** [comment]
To work around borrow checker issues, it might be necessary to return the `(Positioning, Texturing, Coloring, Skinning, Extras)` quintet from `gltf::mesh::Primitives` (iterator) instead of `gltf::mesh::Primitive`. We can look to provide the current version `gltf::mesh::Primitive` another time.

**Comment by alteous** [comment]
I have a type checked prototype available in the [`mikk-tspace`](https://github.com/alteous/gltf/tree/mikk-tspace) branch.

**Comment by alteous** [comment]
After some discussion on gitter, the `(Positioning, Texturing, Coloring, Skinning)` properties idea has been dropped in favour of a universal ordering type (currently `Order`, but naming is subject to change.)

**Comment by alteous** [comment]
A new draft is available - see https://github.com/alteous/gltf/blob/mikk-tspace/src/mesh.rs

**Comment by bwasty** [comment]
Nice! Looks good so far and `indices_u32()`/`tex_coords_f32()` work as expected.

**Comment by alteous** [comment]
You've probably noticed this already but N.B you'll run into `unimplemented!()` if normals or tangents are unavailable.

**Comment by alteous** [comment]
I'm really struggling to come up with a suitable abstraction for tangent and normal generation. It's quite straightforward to create an abstraction over normal generation *or* tangent generation, but not both. Even delegating to the user has its set own problems.

**Comment by alteous** [comment]
I think this should be delegated to the user and documented as such. We could instead provide a reference implementation in the documentation.

**Comment by alteous** [comment]
Closed since clone of https://github.com/alteous/gltf/issues/22
