### ISSUE TITLE
Reduce build times

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#66]
The crate build time is getting out of hand (again), and it affects the iteration time of other projects too. People may be dissuaded from using `gltf` if this continues for too long, so it's important we do something about this sooner rather than later. The trouble is, I have no idea what to do about it. So, if you have any ideas, please discuss!

**Comment by Ralith** [comment]
Making all the high-level magic (especially the futures stuff) opt-in via a cargo feature would undoubtedly reduce compiletimes dramatically for people who don't want them.

**Comment by torkleyy** [comment]
Alternatively, you could just split the crate into `gltf_core` and `gltf`.

**Comment by alteous** [comment]
@torkleyy By putting the JSON parsing and validation in another crate, the build time seems to have improved dramatically, so thanks!

**Comment by alteous** [comment]
I'm pleased to announce that build times are no longer an issue. :D
