### ISSUE TITLE
[features] is messed up

### ISSUE THREAD

**Issue by fst3a** [alteous/gltf#71]
https://github.com/alteous/gltf/blob/master/Cargo.toml#L26

```
[features]
default = []
extras = ["gltf-json/names"]
names = ["gltf-json/extras"]
```

**Comment by alteous** [comment]
Well spotted! That explains @bwasty 's build error from glitter. Will fix asap.

**Comment by alteous** [comment]
The new [`gltf-tree`](https://github.com/alteous/gltf/blob/master/Cargo.toml#L36) example depends on the `names` feature. This should prevent this issue in future releases.

**Comment by alteous** [comment]
I think this is fixed now.
