### ISSUE TITLE
Idea: Add gltf-utils crate

### ISSUE THREAD

**Issue by alteous** [alteous/gltf#74]
The new `Loaded` type was designed to add extra functionality to the basic 'tree-traversal' library (`gltf`). This functionality may be better suited in its own crate.

Example contents:

```rust
gltf_utils::iter_accessor<T: Copy>(accessor: &gltf::Primitive, source: &gltf_utils::Source) -> Iter<T>

extern crate gltf;
extern crate gltf_utils;

use gltf_utils::iter_accessor;

for position in iter_accessor::<cgmath::Point3<f32>>(&position_accessor, &buffer_source) {
   ...
}

gltf_utils::colors(primitive: &Primitive) -> gltf_utils::Colors
gltf_utils::generate_flat_normals(primitive: &Primitive) -> Vec<(usize, [f32; 3])>
```
Source would be moved to gltf_utils.

**Comment by alteous** [comment]
Non-exhaustive list of what would be moved.

 * All accessor abstractions from the `mesh` module (`Positions`, `Colors`, `TexCoords`, `Indices`, etc.)
 * The `Source` trait.
 * The `Glb` type and its implementation from `gltf-importer`.

**Comment by alteous** [comment]
See https://github.com/alteous/gltf/tree/simplify for draft implementation.

**Comment by bwasty** [comment]
I'm still not entirely convinced of the idea, though it's started to grow on me.

As for `Glb`/`gltf-importer` - it would be good to refactor the code to make it more reusable. As far as I saw, I'd have to copy large parts with minor changes to re-implement my old HTTP Source (esp. relating to GLB and Validation).
Also - data URI decoding is gone at the moment, right? #46 says it's moved, but I don't see it anywhere.

General remark: I hope the crate stabilises soon. So far I've had no problem with the breaking changes, but this feels like one too much (in such a short time).

**Comment by bwasty** [comment]
I had the feeling this will create an imbalance between the crates, so maybe it's helpful to list what each would contain:
* `gltf-json`
  - json structs, mapping 1:1
  - validation
* `gltf`
  - Wrapper structs around json structs, replacing indices with references
* `gltf-importer`
  - File-based import helper
  - Config (currently only for validation)
* `gltf-utils`
  - Convenience iterators for geometry
  - `Source`
  - `Glb`
  - normal + tangent generation

If I haven't forgotten something, `gltf` looks a bit thin and doesn't provide much on its own.

Another topic: Extensions. On Gitter it came up that there are two struct variants per entity, e.g. `extensions::Primitive`, `json::extensions::Primitive`. I don't quite understand the design (-> are those structs really needed?). How would implementing an extension work? Perhaps it would be worth trying to add [KHR_materials_pbrSpecularGlossiness](https://github.com/KhronosGroup/glTF/blob/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness/README.md) to see if it works well. It's pretty simple and the only finished extension so far.

**Comment by alteous** [comment]
> gltf looks a bit thin and doesn't provide much on its own

I think this ok. It means build times will be reasonable and from the user's perspective the crate won't be trying to do too much on their behalf.

The way `Gltf` is constructed needs to be revised. Calling `gltf::json::from_x` then `Gltf::from_json` is not intuitive`.

`.glb` files seem ubiquitous enough that its parser should probably be in the main `gltf` crate and not `gltf-utils`. Would you agree?

As for extensions, we should probably implement one and think about the design then. `KHR_materials_pbrSpecularGlossiness` is a simple candidate, as you mention.

White board ideas for `Gltf` / `Glb` parsing:

```rust
//! All included within the `gltf` crate.

impl Gltf {
    pub fn from_slice(data: &[u8]) -> Result<Self, Error> {
        let json = json::from_slice(data)?;
        Gltf::from_json(json)
    }
}

/// `.glb` parsing module.
pub mod glb {
    struct Glb<'a> {
        gltf: Gltf,
        blob: Option<&'a [u8]>,
    }

    pub fn is_glb(data: &[u8]) -> bool {
        data.starts_with(b"glTF")
    }

    impl<'a> Glb<'a> {
        pub fn from_slice(data: &'a [u8]) -> Result<Self, Error> {
            ...
        }
    }

    impl<'a> ::std::ops::Deref for Glb<'a> {
        type Target = Gltf;
        fn deref(&self) -> &Self::Target {
            &self.gltf
        }
    }
}
```

**Comment by alteous** [comment]
> General remark: I hope the crate stabilises soon. So far I've had no problem with the breaking changes, but this feels like one too much (in such a short time).

I understand where you're coming from here, and I do hope so too. I'm solely to blame for the wildly different design choices in each release, but I do this because once the crate is in real-world use it's much harder to make breaking changes. I hope for our combined sanity that the next release is the last major redesign!

Thanks for your patience.

**Comment by bwasty** [comment]
> .glb files seem ubiquitous enough that its parser should probably be in the main gltf crate and not gltf-utils. Would you agree?

Yes.

About the code snippet: I don't quite like the Deref-pattern. It's good for (smart) pointers and strings; for other types I don't normally expect it and may overlook it in the docs (happened twice already). But if the docs fit on "one page" it might be fine.

**Comment by alteous** [comment]
I agree. It's probably best to avoid using `Deref` where possible.

In the `simplify` branch I've added the [glb parsing code](https://github.com/alteous/gltf/blob/simplify/src/glb.rs#L12-L23) and leave the user to construct `Gltf` from it.

What do you think of [this idea](https://github.com/alteous/gltf/blob/simplify/src/gltf.rs#L166-L233) to simplify validation?

**Comment by bwasty** [comment]
Looks pretty good. 
Very minor nitpick: The return type `Result<Unvalidated, Error>` looks a bit weird on it's own (...what's `Unvalidated` supposed to be?).

**Comment by alteous** [comment]
`gltf::Unvalidated` means 'unvalidated glTF`. Please suggest a better name if you can!

**Comment by alteous** [comment]
I tried using a type parameter `Unvalidated<T>` and having an `Unvalidated<Gltf>` elsewhere but it felt overkill.

**Comment by bwasty** [comment]
Couldn't think of something better; my only idea was `UnvalidatedGltf` :)

**Comment by alteous** [comment]
Moving the discussion over to #78
